### ISSUE TITLE
Enquiry the paper and code

### ISSUE THREAD

**Issue by DanielMing123** [wzzheng/TPVFormer#1]
Hello author, I'm very interested in your research, and I want to know when this paper will be published, and the code will go to open source—looking forward to seeing the paper and source code.

**Comment by wzzheng** [comment]
Thanks for your interest! 
We expect the paper to be released next week and the code next month.

**Comment by FrontierBreaker** [comment]
It seems that 2 weeks have gone. Have you released the paper? 💯

**Comment by YoushaaMurhij** [comment]
And the code, please!

**Comment by scuizhibin** [comment]
Hello author, can you write a blog to introduce your ideas?

**Comment by wzzheng** [comment]
Due to some patent issues, we could not release the paper back then.
Thankfully, these issues can probably be resolved within this week.
If not, I will release the code first and introduce my ideas here this weekend.
Thank you all for your patience.

**Comment by scuizhibin** [comment]
> Due to some patent issues, we could not release the paper back then. Thankfully, these issues can probably be resolved within this week. If not, I will release the code first and introduce my ideas here this weekend. Thank you all for your patience.

How often does the author update the code?

**Comment by wzzheng** [comment]
The code has been released! 
Feel free to ask anything.
Paper will be released next week.

**Comment by scuizhibin** [comment]
请问怎么给每个点云做标签？这个是怎么完成的？


---Original---
From: &quot;Wenzhao ***@***.***&gt;
Date: Sun, Feb 12, 2023 21:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Enquiry the paper and code (Issue #1)




 
The code has been released!
 Feel free to ask anything.
 Paper will be released next week.
 
&mdash;

**Comment by wzzheng** [comment]
> 请问怎么给每个点云做标签？这个是怎么完成的？
> […](#)
> ---Original--- From: &quot;Wenzhao ***@***.***&gt; Date: Sun, Feb 12, 2023 21:53 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [wzzheng/TPVFormer] Enquiry the paper and code (Issue #1) The code has been released! Feel free to ask anything. Paper will be released next week. &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Panoptic nuScenes上有这个标签的

**Comment by scuizhibin** [comment]
好的，谢谢


---Original---
From: &quot;Wenzhao ***@***.***&gt;
Date: Tue, Feb 14, 2023 19:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Enquiry the paper and code (Issue #1)




  
请问怎么给每个点云做标签？这个是怎么完成的？
 …
 ---Original--- From: "Wenzhao @.&gt; Date: Sun, Feb 12, 2023 21:53 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [wzzheng/TPVFormer] Enquiry the paper and code (Issue #1) The code has been released! Feel free to ask anything. Paper will be released next week. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Panoptic nuScenes上有这个标签的
 
&mdash;
