### ISSUE TITLE
why you have so many name for the transformer

### ISSUE THREAD

**Issue by AndyYuan96** [wzzheng/TPVFormer#16]
Hi, thanks for sharing the code and paper. After reading the code and the paper, I'm confused with many name like ICA、CVHA、HCAB、HAB。but in code，it looks like there are only two kind transformer layer，selfattention and crossattention。what‘s more，why the transformer config have different in lidarseg and occupancy config，should they only have difference on output？
thanks for kindly reply。

**Comment by huang-yh** [comment]
Hi, Image Cross-Attention (ICA) and Cross-View Hybrid-Attention (CVHA) refer to two kinds of attention mechanisms, while Hybrid-Cross-Attention Block (HCAB) and Hybrid-Attention Block (HAB) refer to two kinds of attention blocks which relates more to actual implementation and also contains LayerNorm and FFN layers in addition to attention layers. 

The self-attention and cross-attention in our code correspond to CVHA and ICA, respectively.

About configs for lidarseg and occupancy, we use different models and supervision signals for these two tasks. But the difference in model structure is trivial, and the tpvformer10 version should also perform well in occupancy prediction task. We keep two different configs only for consistency with the paper, since the visualizations in the paper are generated with tpvformer04.
