### ISSUE TITLE
Question on hybrid ref pt 2d

### ISSUE THREAD

**Issue by george0407** [wzzheng/TPVFormer#24]
```
        ref_2d_hw = self.ref_2d_hw.clone().expand(bs, -1, -1, -1)
        hybird_ref_2d = torch.cat([ref_2d_hw, ref_2d_hw], 0)
```
Firstly appreciate your work, 
and I wonder why you concatenate the ref pts of hw for 2 layers as shown above.
Thanks a lot.

**Comment by huang-yh** [comment]
Hi, the code is built upon BEVFormer. BEVFormer has both temporal version and spatial-only version. BEVFormer concatenates the current ref_2d and the aligned ref_2d_shift from another timestamp in its temporal version, while concatenating two same ref_2ds for the spatial-only version.
Since TPVFormer does not use temporal information, we simply follow the practice of BEVFormer.

**Comment by george0407** [comment]
Thanks for your answer
