### ISSUE TITLE
duplicated question

### ISSUE THREAD

**Issue by seoho-kang** [wzzheng/TPVFormer#45]

**Comment by droneRL2020** [comment]
Also, I am confused with prediction and voxel shape. Since, w and h were always same in config setting this did not cause error but if not, I got shape mismatch error between voxel label and voxel prediction.

https://github.com/wzzheng/TPVFormer/blob/main/config/tpv04_occupancy.py#L34
https://github.com/wzzheng/TPVFormer/blob/main/dataloader/dataset_wrapper.py#L88
Based on above two, val_vox_label in train.py shape is (~, h,w, ~)

https://github.com/wzzheng/TPVFormer/blob/main/tpvformer04/tpv_aggregator.py#L95
However, because of this output the corresponding pred shape seems to be (~, w,h, ~)
